package httpreq

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"io"
	"net/http"
	"os"
	"runtime"
)

// XMLCharDecoder defines a function type that takes a charset and stream of
// bytes that's not encoded in UTF-8 through an io.Reader, and returns another
// io.Reader returns bytes from the input into bytes encoded into UTF-8.
type XMLCharDecoder func(charset string, input io.Reader) (io.Reader, error)

// Response represents the result of an HTTP request
type Response struct {
	// OK indicates whether the server returned a 2xx code
	OK bool

	// Error contains any error that may have occurred during the request.
	Error error

	// RawResponse contains the http.Response object generated by downstream
	// mechanisms.
	RawResponse *http.Response

	// StatusCode represents the HTTP Status Code returned by the server.
	StatusCode int

	// Header contains the set of headers returned by the server.
	Header http.Header

	internalByteBuffer *bytes.Buffer
}

func buildResponse(resp *http.Response, err error) (*Response, error) {
	if err != nil {
		return &Response{Error: err}, err
	}

	goodResp := &Response{
		OK:                 resp.StatusCode >= 200 && resp.StatusCode < 300,
		RawResponse:        resp,
		StatusCode:         resp.StatusCode,
		Header:             resp.Header,
		internalByteBuffer: &bytes.Buffer{},
	}
	ensureResponseFinalized(goodResp)
	return goodResp, nil
}

func (r *Response) Read(p []byte) (n int, err error) {
	if r.Error != nil {
		return -1, r.Error
	}

	return r.RawResponse.Body.Read(p)
}

func (r *Response) Close() error {
	if r.Error != nil {
		return r.Error
	}

	if _, err := io.Copy(io.Discard, r); err != nil && err != io.EOF {
		return err
	}

	return r.RawResponse.Body.Close()
}

// DownloadToFile downloads the contents of the response to a provided
// path.
func (r *Response) DownloadToFile(fileName string) error {
	if r.Error != nil {
		return r.Error
	}

	fd, err := os.Create(fileName)
	if err != nil {
		return err
	}

	defer func() { _ = r.Close() }()
	defer func() { _ = fd.Close() }()

	if _, err := io.Copy(fd, r.getInternalReader()); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (r *Response) getInternalReader() io.Reader {
	if r.internalByteBuffer.Len() != 0 {
		return r.internalByteBuffer
	}
	return r
}

// XML unmarshals the obtained response body into the provided userStruct pointer.
func (r *Response) XML(userStruct any, charsetReader XMLCharDecoder) error {
	if r.Error != nil {
		return r.Error
	}

	xmlDecoder := xml.NewDecoder(r.getInternalReader())

	if charsetReader != nil {
		xmlDecoder.CharsetReader = charsetReader
	}

	defer func() { _ = r.Close() }()

	return xmlDecoder.Decode(&userStruct)
}

// JSON unmarshals the obtained response body into the provided userStruct pointer.
func (r *Response) JSON(userStruct any) error {
	if r.Error != nil {
		return r.Error
	}

	jsonDecoder := json.NewDecoder(r.getInternalReader())
	defer func() { _ = r.Close() }()

	return jsonDecoder.Decode(&userStruct)
}

func (r *Response) populateResponseByteBuffer() {
	if r.internalByteBuffer.Len() != 0 {
		return
	}

	defer func() { _ = r.Close() }()

	if r.RawResponse.ContentLength == 0 {
		return
	}

	if r.RawResponse.ContentLength > 0 {
		r.internalByteBuffer.Grow(int(r.RawResponse.ContentLength))
	}

	if _, err := io.Copy(r.internalByteBuffer, r); err != nil && err != io.EOF {
		r.Error = err
		_ = r.RawResponse.Body.Close()
	}
}

// Bytes returns the response body as a byte slice
func (r *Response) Bytes() []byte {
	if r.Error != nil {
		return nil
	}

	r.populateResponseByteBuffer()
	if r.internalByteBuffer.Len() == 0 {
		return nil
	}

	return r.internalByteBuffer.Bytes()
}

// String returns the response body as a string
func (r *Response) String() string {
	if r.Error != nil {
		return ""
	}

	r.populateResponseByteBuffer()

	return r.internalByteBuffer.String()
}

// ClearInternalBuffer clears the internal buffer that maintains data used by
// String and Bytes.
func (r *Response) ClearInternalBuffer() {
	if r == nil || r.internalByteBuffer == nil {
		return
	}

	r.internalByteBuffer.Reset()
}

func ensureResponseFinalized(httpResp *Response) {
	runtime.AddCleanup(httpResp, func(r **Response) {
		if r == nil || *r == nil {
			return
		}
		_ = (*r).RawResponse.Body.Close()
	}, &httpResp)
}
